# Default values for btg-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# =================================================================
# =========  Deployment configuration
replicaCount: 1

# Bitcoin Global configs
image:
  registry: eu.gcr.io
  repository: bitcoin-global-playground/btg-node
  tag: bootstrap
  pullPolicy: IfNotPresent
  pullSecrets: 
    name: docker-pull-secrets

# Container command
command:
- bitglobd 
- -testnet
- -bootstrap

# User data
rpc:
  secret: rpc-data
  user: username

# ========= Data configuration
volumeName: bitcoin-global-data
volumes:
  - name: bitcoin-global-data
    gcePersistentDisk:
      pdName: bitcoin-global-data
      fsType: ext4

# ========= Services configuration
service:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    bitglobal:
      mainnet: 8222
      testnet: 18222
    bitcoin:
      mainnet: 8333
      testnet: 18333

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## =================================================================
## Configure resource requests and limits
resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    # cpu: 100m
    memory: 2Gi

# Run on preemptive cluster.
tolerations:
  - effect: NoSchedule
    key: task
    operator: Equal
    value: preemptive

nodeSelector: {}
affinity: {}
